version: "3"
services:
  preorder:
    container_name: preorder
    image: mysql:latest
    restart: always
    volumes:
      - mysql_volume:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=1234
      - MYSQL_DATABASE=preorder
      - MYSQL_USER=puser
      - MYSQL_PASSWORD=1234
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8081"
    depends_on:
      - preorder
    networks:
      - pre

networks:
  pre:
    driver: bridge

volumes:
  mysql_volume:
    driver: local
